fixtures:
  symlinks:
    nodesite: '#{source_dir}'
  forge_modules:
      firewall: "puppetlabs/firewall"
      stdlib:
          repo: "puppetlabs/stdlib"
          ref: "3.2.0"
      git:
          repo: "example42/git"
          ref:  "2.0.x"
      nodejs:
          repo: "willdurand/nodejs"
          ref:  "1.8.5"
      wget:
          repo: "maestrodev/wget"
          ref:  "1.5.6"
      epel:
          repo: "stahnma/epel"
          ref:  "1.1.1"
      logrotate:
          repo: "rodjek/logrotate"
          ref:  "1.1.1"
